### ISSUE TITLE
Error database when attempting to install

### ISSUE THREAD

**Issue by danuthintariu** [SMFTricks/Topic-Solved#2]
Hi, i get this error went i try to install the Mod.

```
DATA BASE ERROR : Data truncated for column 'is_solved' at row 11


		ALTER TABLE smf_topics
		CHANGE COLUMN `is_solved` `is_solved` tinyint(3) unsigned NOT NULL default '0'  
```

**Comment by DiegoAndresCortes** [comment]
Could you provide info about your setup?
In any case, try changing the column type to smallint.

**Comment by danuthintariu** [comment]
Now is working, the problem was that column "is_solved" was already existent in my data base with some data saved in it and looks like is used be another mod (I'm not 100% sure, I'll check this when I have more free time.).

I solved the problem by changing the mod to use the name "iss_solved" and "cans_solve" because i don't want to brake anything else.

For now I noted this and in the future I will know if there are new updates to keep the same name.
